#!/bin/bash
SERVER_PROPERTIES=server.properties
CRAFTBUKKIT_SERVER_JAR=craftbukkit.jar

set -x 

cd $OPENSHIFT_DATA_DIR

if [ ! -e "$CRAFTBUKKIT_SERVER_JAR" ]; then
	wget "http://dl.bukkit.org/downloads/craftbukkit/get/02342_1.6.2-R1.0/craftbukkit.jar" -O $CRAFTBUKKIT_SERVER_JAR
fi

